all:
  children:
    docker_nodes:
      hosts:
          docker-worker1:
            ansible_python_interpreter: /usr/bin/python3
            ansible_connection: ssh
            ansible_ssh_user: vagrant
            ansible_host: 192.168.33.11 # Remote host
            ansible_port: 22
          docker-worker2:
            ansible_python_interpreter: /usr/bin/python3
            ansible_connection: ssh
            ansible_ssh_user: vagrant
            ansible_host: 192.168.33.12 # Remote host
            ansible_port: 22
          docker-worker3:
            ansible_python_interpreter: /usr/bin/python3
            ansible_connection: ssh
            ansible_ssh_user: vagrant
            ansible_host: 192.168.33.13 # Remote host
            ansible_port: 22