all:
    hosts:
      containers_dev:
        ansible_python_interpreter: /usr/bin/python3
        ansible_connection: ssh
        ansible_ssh_user: root
        ansible_host: 10.77.10.9 # Remote host
        ansible_port: 22
        