--- 
# sudo apt-get update
- name: Update apt packages
  apt:
    update_cache: yes
  tags:
    - system

- name: Upgrade all packages to the latest version
  apt:
    name: "*"
    state: latest
  tags:
    - system
 
- name: Ensure hostname set
  raw:  "hostnamectl set-hostname {{ inventory_hostname }}"

- name: Ensure hostname is in /etc/hosts
  lineinfile:
    dest=/etc/hosts
    regexp="^{{ ansible_default_ipv4.address }}.+$"
    line="{{ ansible_default_ipv4.address }} {{ ansible_fqdn }} {{ inventory_hostname }}"

# Import docker tasks
- name: Importing docker tasks
  include_tasks: 02-docker.yml

# Import users tasks
- name: Running users import and configuring
  include_tasks: 03-create-users.yml
 
# sudo apt-get autoclean
- name: Remove useless apt packages from the cache
  apt:
    autoclean: yes
  tags:
    - system
 
# sudo apt-get autoremove
- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes
  tags:
    - system